const ctnlCookies = [
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1594372657.308738,
      "hostOnly": false,
      "httpOnly": true,
      "name": "__cfduid",
      "path": "/",
      "sameSite": "lax",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "d3b4dbaf8f90ddf7221fe758981bea13a1591780659",
      "id": 1
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1656504099,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_ga",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "GA1.2.204842784.1591780658",
      "id": 2
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593436427,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_gali",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "queueComponent_28",
      "id": 3
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593518499,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_gid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "GA1.2.2071845820.1593431989",
      "id": 4
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1654852661,
      "hostOnly": false,
      "httpOnly": false,
      "name": "cookieConsentLevel",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "functional",
      "id": 5
  },
  {
      "domain": "www.cheaptickets.nl",
      "expirationDate": 1656081027,
      "hostOnly": true,
      "httpOnly": false,
      "name": "cookieConsentLevel",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "functional",
      "id": 6
  }
];

const dwCookies = [
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1594372657.308738,
      "hostOnly": false,
      "httpOnly": true,
      "name": "__cfduid",
      "path": "/",
      "sameSite": "lax",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "d3b4dbaf8f90ddf7221fe758981bea13a1591780659",
      "id": 1
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1656598054,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_ga",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "GA1.2.204842784.1591780658",
      "id": 2
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593526110,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_gat_UA-11465007-1",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "1",
      "id": 3
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593526110,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_gat_UA-49709845-16",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "1",
      "id": 4
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593526110,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_gat_UA-49709845-18",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "1",
      "id": 5
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593612454,
      "hostOnly": false,
      "httpOnly": false,
      "name": "_gid",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "GA1.2.2071845820.1593431989",
      "id": 6
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1593529156,
      "hostOnly": false,
      "httpOnly": false,
      "name": "AMP_TOKEN",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "%24NOT_FOUND",
      "id": 7
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1625062052,
      "hostOnly": false,
      "httpOnly": false,
      "name": "contentshowversion",
      "path": "/",
      "sameSite": "no_restriction",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "DYNAMICWEB_APPLIED",
      "id": 8
  },
  {
      "domain": ".cheaptickets.nl",
      "expirationDate": 1654852661,
      "hostOnly": false,
      "httpOnly": false,
      "name": "cookieConsentLevel",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "functional",
      "id": 9
  },
  {
      "domain": "www.cheaptickets.nl",
      "expirationDate": 1656597590,
      "hostOnly": true,
      "httpOnly": false,
      "name": "cookieConsentLevel",
      "path": "/",
      "sameSite": "unspecified",
      "secure": false,
      "session": false,
      "storeId": "0",
      "value": "functional",
      "id": 10
  }
];

module.exports = {
  ctnlCookies,
  dwCookies,
}